package com.example.quizzerApp.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

/**
 * Entity representing an answer option for a quiz question.
 * Each question can have multiple answer options, with one or more marked as
 * correct.
 */
@Entity
public class AnswerOption {

    /**
     * Unique identifier for the answer option.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The text content of the answer option.
     */
    private String text;

    /**
     * Indicates whether this answer option is correct.
     * Used to evaluate user responses.
     */
    private boolean isCorrect;

    /**
     * The question that this answer option belongs to.
     * Many-to-one relationship with Question entity.
     * JsonIgnoreProperties prevents infinite recursion during serialization.
     */
    @ManyToOne
    @JoinColumn(name = "question_id")
    @JsonIgnoreProperties("answers") // Prevents circular references
    private Question question;

    /**
     * Retrieves the ID of the answer option.
     *
     * @return The answer option ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the ID of the answer option.
     *
     * @param id The answer option ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the text content of the answer option.
     *
     * @return The answer option text
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the text content of the answer option.
     *
     * @param text The answer option text to set
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Checks if this answer option is marked as correct.
     *
     * @return true if this answer is correct, false otherwise
     */
    public boolean isCorrect() {
        return isCorrect;
    }

    /**
     * Sets whether this answer option is correct.
     *
     * @param isCorrect The correct status to set
     */
    public void setCorrect(boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    /**
     * Retrieves the question that this answer option belongs to.
     *
     * @return The parent question
     */
    public Question getQuestion() {
        return question;
    }

    /**
     * Sets the question that this answer option belongs to.
     * Establishes the many-to-one relationship.
     *
     * @param question The parent question to set
     */
    public void setQuestion(Question question) {
        this.question = question;
    }
}